//! Project media evidence catalogue (§24, Phase 11) built on `tpt-av-asset`.
//!
//! Media evidence (screenshots, photos, audio and video recordings) is
//! stored as immutable project assets (see [`crate::store`]); this module
//! catalogues those media files and derives cached artifacts:
//!
//! * every media asset is registered in an `AssetDb` (path, size, media
//!   type, audio metadata for WAV recordings) so the UI can list and query
//!   project media without re-reading files;
//! * audio recordings get a waveform peak cache (`.peaks`, min/max/RMS per
//!   fixed chunk) generated by `tpt-av-asset-cache`'s resumable generator —
//!   real-time-safe reads for waveform display come from `WaveformReader`.
//!
//! The catalogue database is opened per operation and dropped: `redb` holds
//! an exclusive lock while open, and the store should never keep it open
//! across user interactions.

use std::path::{Path, PathBuf};

use tpt_app_av_commissioning_model::{EvidenceKind, EvidenceRef};
use tpt_app_av_commissioning_test::audio::read_wav;
use tpt_av_asset_cache::{CacheStorage, WaveformCache, WaveformGenerator};
use tpt_av_asset_db::AssetDb;
use tpt_av_asset_utils::{AssetId, MediaInfo, MediaType, ProgressReporter};

/// Waveform chunk size for peak caches (samples per chunk).
const WAVEFORM_CHUNK_SIZE: u32 = 1024;

/// Errors from the media catalogue.
#[derive(Debug, thiserror::Error)]
pub enum MediaError {
    #[error("asset error: {0}")]
    Asset(#[from] tpt_av_asset_utils::AssetError),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("audio error: {0}")]
    Audio(#[from] tpt_app_av_commissioning_test::AudioError),
}

/// The project's catalogue of media evidence files and derived artifacts.
pub struct MediaCatalog {
    db: AssetDb,
    storage: CacheStorage,
}

impl MediaCatalog {
    /// Open (creating if needed) the catalogue under the project assets
    /// root: the media database at `assets/media.redb` and the derived
    /// artifact cache at `assets/cache/`.
    pub fn open(assets_root: &Path) -> Result<Self, MediaError> {
        let storage = CacheStorage::new(assets_root.join("cache"));
        storage.ensure_layout()?;
        let db = AssetDb::open(&assets_root.join("media.redb"))?;
        Ok(Self { db, storage })
    }

    /// Whether the evidence kind is media this catalogue tracks.
    pub fn media_type(kind: EvidenceKind) -> Option<MediaType> {
        match kind {
            EvidenceKind::AudioRecording => Some(MediaType::Audio),
            EvidenceKind::VideoRecording => Some(MediaType::Video),
            EvidenceKind::Screenshot | EvidenceKind::Photo => Some(MediaType::Image),
            _ => None,
        }
    }

    /// Register a media evidence file. Returns the stored `MediaInfo`, or
    /// `None` for evidence kinds that are not media (notes, measurements…).
    ///
    /// Audio WAV recordings get their audio metadata (sample rate, channels,
    /// duration) extracted.
    pub fn register(
        &mut self,
        evidence: &EvidenceRef,
        file: &Path,
    ) -> Result<Option<MediaInfo>, MediaError> {
        let Some(media_type) = Self::media_type(evidence.kind) else {
            return Ok(None);
        };
        let asset_id = AssetId::from_path(file)?;
        let mut info = MediaInfo::new(asset_id, file, media_type);
        info.size = std::fs::metadata(file)?.len();
        if media_type == MediaType::Audio {
            info.audio = audio_info(file)?;
            if let Some(audio) = &info.audio {
                info.duration_secs = Some(audio.duration_secs);
            }
        }
        self.db.upsert_asset(&info)?;
        Ok(Some(info))
    }

    /// All registered media assets.
    pub fn list(&self) -> Result<Vec<MediaInfo>, MediaError> {
        Ok(self.db.list_assets()?)
    }

    /// The registered media asset for a file path, if any.
    pub fn lookup(&self, file: &Path) -> Result<Option<MediaInfo>, MediaError> {
        Ok(self.db.get_asset_by_path(file)?)
    }

    /// Generate (or resume) the waveform peak cache for an audio recording
    /// and return the `.peaks` path. Non-audio files are rejected.
    pub fn waveform(&mut self, file: &Path) -> Result<PathBuf, MediaError> {
        let asset_id = AssetId::from_path(file)?;
        let mut cache = WaveformCache::open(asset_id, &self.storage)?;
        // Chunk size is fixed; the generator adapts to the source rate.
        let sample_rate = audio_info(file)?.map(|a| a.sample_rate).unwrap_or(48_000);
        let generator = WaveformGenerator::new(WAVEFORM_CHUNK_SIZE, sample_rate);
        generator.generate(file, &mut cache, &ProgressReporter::new())?;
        cache.finish()?;
        Ok(self.storage.waveform_path(asset_id))
    }
}

/// Extract audio metadata from a WAV evidence file.
fn audio_info(file: &Path) -> Result<Option<tpt_av_asset_utils::AudioInfo>, MediaError> {
    let (sample_rate, samples) = match read_wav(file) {
        Ok(parsed) => parsed,
        // Not a WAV (or undecodable): catalogue it without audio metadata.
        Err(tpt_app_av_commissioning_test::AudioError::Codec(_)) => return Ok(None),
        Err(e) => return Err(e.into()),
    };
    let duration_secs = if sample_rate > 0 {
        samples.len() as f64 / sample_rate as f64
    } else {
        0.0
    };
    Ok(Some(tpt_av_asset_utils::AudioInfo {
        sample_rate,
        channels: 1,
        bit_depth: 16,
        codec: "pcm".to_owned(),
        bit_rate: Some(sample_rate as u64 * 16),
        duration_secs,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::ProjectStore;
    use tpt_app_av_commissioning_model::{EvidenceKind, ProjectId};
    use tpt_app_av_commissioning_test::audio::{generate_tone, write_wav};
    use tpt_app_av_commissioning_test::ToneSpec;

    fn store() -> (ProjectStore, PathBuf) {
        let dir = std::env::temp_dir().join(format!(
            "tpt-media-{}-{}",
            std::process::id(),
            uuid::Uuid::new_v4()
        ));
        let store = ProjectStore::create(
            &dir,
            &crate::store::ProjectMeta {
                id: ProjectId::new("prj-1"),
                name: "Media".into(),
                client: None,
                site: None,
            },
        )
        .unwrap();
        (store, dir)
    }

    #[test]
    fn only_media_kinds_are_catalogued() {
        assert_eq!(
            MediaCatalog::media_type(EvidenceKind::Screenshot),
            Some(MediaType::Image)
        );
        assert_eq!(
            MediaCatalog::media_type(EvidenceKind::Photo),
            Some(MediaType::Image)
        );
        assert_eq!(
            MediaCatalog::media_type(EvidenceKind::AudioRecording),
            Some(MediaType::Audio)
        );
        assert_eq!(
            MediaCatalog::media_type(EvidenceKind::VideoRecording),
            Some(MediaType::Video)
        );
        assert_eq!(MediaCatalog::media_type(EvidenceKind::OperatorNote), None);
        assert_eq!(MediaCatalog::media_type(EvidenceKind::Measurement), None);
        assert_eq!(MediaCatalog::media_type(EvidenceKind::NetworkResult), None);
        assert_eq!(MediaCatalog::media_type(EvidenceKind::DeviceResponse), None);
        assert_eq!(MediaCatalog::media_type(EvidenceKind::Configuration), None);
    }

    #[test]
    fn audio_evidence_is_catalogued_with_waveform_peaks() {
        let (store, dir) = store();
        let samples = generate_tone(&ToneSpec {
            frequency_hz: 1000.0,
            level_dbfs: -6.0,
            duration_ms: 200, // 9600 samples at 48 kHz
            sample_rate_hz: 48_000,
        });
        // Encode to a scratch file, then add it as a proper evidence asset.
        let scratch = dir.join("tone-scratch.wav");
        write_wav(&samples, 48_000, &scratch).unwrap();
        let wav = std::fs::read(&scratch).unwrap();
        let _ = std::fs::remove_file(&scratch);
        let evidence = store
            .assets()
            .add_evidence(
                "run-1",
                &ProjectId::new("prj-1"),
                EvidenceKind::AudioRecording,
                &wav,
                "wav",
                Some("1 kHz test tone".into()),
            )
            .unwrap();
        let file = dir.join(&evidence.relative_path);

        let mut catalog = MediaCatalog::open(&dir.join("assets")).unwrap();
        let info = catalog.register(&evidence, &file).unwrap().unwrap();
        assert_eq!(info.media_type, MediaType::Audio);
        let audio = info.audio.as_ref().unwrap();
        assert_eq!(audio.sample_rate, 48_000);
        assert!((audio.duration_secs - 0.2).abs() < 0.01);

        // Waveform peaks: 9600 samples / 1024 = 10 chunks (9 full + rest).
        let peaks = catalog.waveform(&file).unwrap();
        assert!(peaks.exists());
        let reader = tpt_av_asset_cache::WaveformReader::open(&peaks).unwrap();
        assert!(reader.chunk_count() >= 9);
        let first = reader.read_chunk(0).unwrap().unwrap();
        // -6 dBFS sine: peaks near ±0.5.
        assert!(first.max > 0.4 && first.max <= 0.55, "max {}", first.max);
        assert!(first.min < -0.4 && first.min >= -0.55, "min {}", first.min);
        assert!(first.rms > 0.2 && first.rms < 0.45, "rms {}", first.rms);
        assert!(!first.is_silent());

        // The catalogue persists across reopen.
        drop(catalog);
        let catalog = MediaCatalog::open(&dir.join("assets")).unwrap();
        assert_eq!(catalog.list().unwrap().len(), 1);
        let found = catalog.lookup(&file).unwrap().unwrap();
        assert_eq!(found.id, info.id);

        drop(store);
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn non_media_evidence_is_not_registered() {
        let (store, dir) = store();
        let evidence = store
            .assets()
            .add_evidence(
                "run-1",
                &ProjectId::new("prj-1"),
                EvidenceKind::OperatorNote,
                b"engineer noted hum at 50 Hz",
                "txt",
                None,
            )
            .unwrap();
        let file = dir.join(&evidence.relative_path);
        let mut catalog = MediaCatalog::open(&dir.join("assets")).unwrap();
        assert!(catalog.register(&evidence, &file).unwrap().is_none());
        assert!(catalog.list().unwrap().is_empty());
        drop(store);
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn screenshots_are_catalogued_as_images() {
        let (store, dir) = store();
        let evidence = store
            .assets()
            .add_evidence(
                "run-1",
                &ProjectId::new("prj-1"),
                EvidenceKind::Screenshot,
                b"\x89PNG-bytes",
                "png",
                None,
            )
            .unwrap();
        let file = dir.join(&evidence.relative_path);
        let mut catalog = MediaCatalog::open(&dir.join("assets")).unwrap();
        let info = catalog.register(&evidence, &file).unwrap().unwrap();
        assert_eq!(info.media_type, MediaType::Image);
        assert!(info.audio.is_none());
        // Size recorded from the file.
        assert_eq!(info.size, std::fs::metadata(&file).unwrap().len());
        drop(store);
        std::fs::remove_dir_all(&dir).unwrap();
    }
}
