[package]
name = "tpt-app-av-commissioning-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
tpt-app-av-commissioning-core.workspace = true
tpt-app-av-commissioning-model.workspace = true
tpt-app-av-commissioning-test.workspace = true
tpt-app-av-commissioning-device.workspace = true
tpt-app-av-commissioning-driver.workspace = true
tpt-app-av-commissioning-runner.workspace = true
tpt-app-av-commissioning-report.workspace = true
tpt-app-av-commissioning-profile.workspace = true
tpt-app-av-commissioning-driver-generic.workspace = true
tpt-app-av-commissioning-driver-osc.workspace = true

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tpt-app-av-commissioning-testkit.workspace = true
