[package]
name = "tpt-app-av-commissioning-tauri"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
tpt-app-av-commissioning-core.workspace = true
tpt-app-av-commissioning-model.workspace = true