[package]
name = "tpt-app-av-commissioning-driver-generic"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Generic text-protocol drivers (TCP, more to follow) for TPT AV Commissioning."
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
serde_json.workspace = true
serialport.workspace = true
tungstenite.workspace = true
tpt-app-av-commissioning-device.workspace = true
tpt-app-av-commissioning-driver.workspace = true
tpt-app-av-commissioning-profile.workspace = true

[dev-dependencies]
tpt-app-av-commissioning-model.workspace = true
tpt-app-av-commissioning-test.workspace = true
